<?php
session_start();
if ($_SESSION['username'] == "") {
    header('location: ../login.php');
    exit;
}
require_once('../../config/db_connect.php');

$search = '';
if (isset($_GET['search'])) {
    $search = $conn->real_escape_string($_GET['search']);
    $sql = "SELECT id, name, phone, address FROM members
            WHERE name LIKE '%$search%' OR phone LIKE '%$search%' OR address LIKE '%$search%'";
} else {
    $sql = "SELECT id, name, phone, address FROM members";
}
$result = $conn->query($sql);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Members - Print</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
    <style>
        :root {
            --brand-primary: #00897b;
            --brand-accent: #ff7043;
        }
        body { padding: 28px; color: #222; }
        .doc-header {
            display: flex;
            align-items: center;
            gap: 16px;
            margin-bottom: 14px;
        }
        .doc-header img {
            height: 64px;
            width: auto;
        }
        .doc-header .titles {
            line-height: 1.2;
        }
        .doc-header .titles h1 {
            font-size: 1.35rem;
            margin: 0;
            color: var(--brand-primary);
            font-weight: 800;
        }
        .doc-header .titles .sub {
            font-size: 0.92rem;
            color: #666;
        }
        .doc-meta {
            display: flex;
            justify-content: space-between;
            align-items: center;
            font-size: 0.9rem;
            padding: 8px 12px;
            border: 1px solid #e0e0e0;
            border-left: 4px solid var(--brand-accent);
            border-radius: 8px;
            margin-bottom: 16px;
            background: #fafafa;
        }
        .table { font-size: 12px; }
        .table thead th { background: #f3f6f8; color: #333; border-bottom: 2px solid #e0e0e0; }
        .table td, .table th { vertical-align: middle; }
        .footer-note { margin-top: 18px; font-size: 0.85rem; color: #666; }
        @media print {
            .no-print { display: none !important; }
            body { padding: 0; }
            .doc-meta { -webkit-print-color-adjust: exact; print-color-adjust: exact; }
        }
    </style>
    <script>
        window.addEventListener('load', function(){
            setTimeout(function(){ window.print(); }, 300);
        });
    </script>
    </head>
<body>
    <div class="d-flex justify-content-between align-items-center mb-3 no-print">
        <h4 class="m-0">Members</h4>
        <button class="btn btn-secondary" onclick="window.close()">Close</button>
    </div>

    <div class="doc-header">
        <img src="../images/logo1.png" alt="Association Logo">
        <div class="titles">
            <h1>Bangkero & Fishermen Association</h1>
            <div class="sub">Members Directory</div>
        </div>
    </div>
    <div class="doc-meta">
        <div>
            Printed on: <strong><?php echo date('F j, Y g:i A'); ?></strong>
        </div>
        <div>
            <?php echo isset($search) && $search !== '' ? 'Filter: "' . htmlspecialchars($search) . '"' : 'All members'; ?>
        </div>
    </div>

    <div class="table-responsive">
        <table class="table table-bordered table-striped align-middle">
            <thead>
                <tr>
                    <th style="width:60px">#</th>
                    <th>Name</th>
                    <th>Contact</th>
                    <th>Address</th>
                </tr>
            </thead>
            <tbody>
                <?php $count = 1; if ($result && $result->num_rows > 0): ?>
                    <?php while ($row = $result->fetch_assoc()): ?>
                        <tr>
                            <td class="text-center"><?php echo $count++; ?></td>
                            <td><?php echo htmlspecialchars($row['name']); ?></td>
                            <td><?php echo htmlspecialchars($row['phone']); ?></td>
                            <td><?php echo htmlspecialchars($row['address']); ?></td>
                        </tr>
                    <?php endwhile; ?>
                <?php else: ?>
                    <tr><td colspan="4" class="text-center text-muted">No members found.</td></tr>
                <?php endif; ?>
            </tbody>
        </table>
    </div>

    <div class="footer-note">
        Generated by BFA Admin System.
    </div>
</body>
</html>


